### PR TITLE
aws_secret_backend: allow role_arns with policy_arns

### LINKED ISSUE #709: vault_aws_secret_backend_role: role_arns conflicts with policy_arns while it should not
### Terraform Version

```
Terraform v0.12.23
```

### Affected Resource(s)

- vault_aws_secret_backend_role

### Terraform Configuration Files
```hcl
resource "vault_aws_secret_backend_role" "ecr" {
  backend         = vault_aws_secret_backend.aws.path
  name            = "ecr"
  credential_type = "assumed_role"

  role_arns = [
    "arn:aws:iam::${local.account_id}:role/${local.role-name}",
  ]

  policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
  ]
}
```

### Expected Behavior
Plan runs successfully, as well as apply.

### Actual Behavior
```

Error: "policy_arns": conflicts with role_arns

  on aws-secret.tf line 47, in resource "vault_aws_secret_backend_role" "ecr":
  47: resource "vault_aws_secret_backend_role" "ecr" {



Error: "role_arns": conflicts with policy_arns

  on aws-secret.tf line 47, in resource "vault_aws_secret_backend_role" "ecr":
  47: resource "vault_aws_secret_backend_role" "ecr" {


```

### Steps to Reproduce
Please list the steps required to reproduce the issue:
1. `terraform plan`

### References

- Seems like this is a config desync with #407 where the case where `credential_type = assumed_role` and both `role_arns` and `policy_arns` has not been tested because it did not exist back then.
- Upstream documentation for Vault does not mention anything about it https://www.vaultproject.io/api-docs/secret/aws/#parameters-3
- Upstream documentation for AWS does seem to mention policy arns are valid for `sts:AssumeRole` https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html (as well as inline ones)

### PR DESCRIPTION
**Pull request by adongy**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #709 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-vault/blob/master/CHANGELOG.md):

```release-note
aws_secret_backend: when `credential_type = assumed_role`, allow `policy_arns`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSecretBackend'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccAWSSecretBackend -timeout 120m
?   	github.com/terraform-providers/terraform-provider-vault	[no test files]
?   	github.com/terraform-providers/terraform-provider-vault/cmd/coverage	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/util	(cached) [no tests to run]
=== RUN   TestAccAWSSecretBackendRole_basic
--- PASS: TestAccAWSSecretBackendRole_basic (0.23s)
=== RUN   TestAccAWSSecretBackendRole_import
--- PASS: TestAccAWSSecretBackendRole_import (0.19s)
=== RUN   TestAccAWSSecretBackendRole_nested
--- PASS: TestAccAWSSecretBackendRole_nested (0.27s)
=== RUN   TestAccAWSSecretBackend_basic
--- PASS: TestAccAWSSecretBackend_basic (0.25s)
=== RUN   TestAccAWSSecretBackend_import
--- PASS: TestAccAWSSecretBackend_import (0.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-vault/vault	1.070s
```

Tests did not update. I let the Vault binary provide validation as done here: https://github.com/hashicorp/vault/blob/master/builtin/logical/aws/path_roles.go

I did not change the code for the deprecated attributes (as they have `Removed`). Website documentation has been copied from the Vault website and reordered.

The sample Terraform has been updated, as only specifying a `policy_document` with `credential_type = assumed_role` is illegal.

Thanks!

### CODE REVIEW

File: vault/resource_aws_secret_backend_role.go [hunk 1]
```diff
@@ -36,10 +36,9 @@ func awsSecretBackendRoleResource() *schema.Resource {
 				Description: "The path of the AWS Secret Backend the role belongs to.",
 			},
 			"policy_arns": {
-				Type:          schema.TypeSet,
-				Optional:      true,
-				ConflictsWith: []string{"policy", "policy_arn", "role_arns"},
```
Comment (tyrannosaurus-becks) [inline vault/resource_aws_secret_backend_role.go]: Hi! I'd be fine with pulling `role_arns` out here. However, I'm not so sure we should pull out the rest. Adding these deprecated parameters to `ConflictsWith` here is a normal part of the best practices around deprecation located [here](https://www.terraform.io/docs/extend/best-practices/deprecations.html).

Comment (adongy) [reply vault/resource_aws_secret_backend_role.go]: Hi!

That does seem reasonable as we're still not at the next major version bump.
