### PR TITLE
Fix wrong response data from gcp_auth_backend_role read request

### LINKED ISSUE #228: Terraform wants to re-create vault_gcp_auth_backend_role every time
### Summary
If I have a `vault_gcp_auth_backend_role` resource, Terraform wants to recreate it on every subsequent run of `terraform apply` (or `terraform plan`,) even if I haven't actually changed the resource.

### Terraform Version
```no-highlight
>terraform -v
Terraform v0.11.10
+ provider.vault v1.2.0
```

### Affected Resource(s)
- vault_gcp_auth_backend_role

### Terraform Configuration Files
I omitted the values of the variables because they are all specific to my environment.
```hcl
provider "vault" {
  address      = "${var.address}"
  token        = "${var.token}"
  ca_cert_file = "${var.ca_cert_file}"
  version      = "~> 1.2"
}

resource "vault_gcp_auth_backend_role" "my_role" {
  role                   = "elabs_developer"
  type                   = "iam"
  project_id             = "${var.project_id}"
  bound_service_accounts = ["${var.bound_service_account}"]
  policies               = ["default"]
  max_ttl                = "2h"
}
```

### Debug Output
https://gist.github.com/RobinsonWM/3cea0f24335e540559e68552402e0fa2

### Expected Behavior
Since I didn't change the resource at all, Terraform should not plan any changes.

### Actual Behavior
Terraform reports changes for the resource:
```no-highlight
>terraform apply
vault_gcp_auth_backend_role.my_role: Refreshing state... (ID: auth/gcp/role/elabs_developer)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ vault_gcp_auth_backend_role.my_role (new resource required)
      id:                                "auth/gcp/role/elabs_developer" => <computed> (forces new resource)
      backend:                           "gcp" => "gcp"
      bound_service_accounts.#:          "1" => "1"
      bound_service_accounts.2121747459: "vault-stage-provisioner@sfmc-qa-poc.iam.gserviceaccount.com" => "vault-stage-provisioner@sfmc-qa-poc.iam.gserviceaccount.com"
      max_ttl:                           "7200" => "2h"
      period:                            "" => <computed>
      policies.#:                        "1" => "1"
      policies.1971754988:               "default" => "default"
      project_id:                        "sfmc-qa-poc" => "sfmc-qa-poc"
      role:                              "elabs_developer" => "elabs_developer"
      ttl:                               "" => <computed>
      type:                              "" => "iam" (forces new resource)


Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce
1. `terraform apply` - on the first run, it creates the resource as expected
1. Don't make any changes in Vault or in the Terraform configuration file
2. `terraform apply` (or `terraform plan`) - it unexpectedly wants to recreate the resource

### Important Factoids
I may have lumped two problems into one issue.

In the example, I expressed `max_ttl` as `2h`.  On the re-run, it sees the current value as `7200` (seconds) and wants to change it back to `2h` even though they represent the same value.

However, if we remove `max_ttl` from the picture, the problem still happens, likely because of `type`.

### PR DESCRIPTION
**Pull request by Phylu**
As of https://github.com/hashicorp/vault-plugin-auth-gcp/commit/438b86d4b944867fc9ca0d713280088eb72df744, the `role_type` field has been changed to `type`.

This pull request should resolve #228.

### CODE REVIEW

**Comment by Phylu** [comment]
Tests seem to fail as the vault version used in the tests (0.11.1) is before the change which renamed the field in vault.

File: vault/resource_gcp_auth_backend_role.go [hunk 1]
```diff
@@ -252,7 +252,7 @@ func gcpAuthResourceRead(d *schema.ResourceData, meta interface{}) error {
 
 	d.Set("ttl", resp.Data["ttl"])
 	d.Set("max_ttl", resp.Data["max_ttl"])
-	d.Set("type", resp.Data["role_type"])
+	d.Set("type", resp.Data["type"])
```
Comment (tyrannosaurus-becks) [inline vault/resource_gcp_auth_backend_role.go]: What about handling both forwards and backwards compatibility? So, for each of them, it would basically be, if `resp.Data["whatever"]` has a value, then `d.Set` it? We could just add a comment that it's for compatibility.

Comment (Phylu) [reply vault/resource_gcp_auth_backend_role.go]: Good idea. I will try to leverage some time for this. We should probably check for 'role_type' (original value), 'role' (wrong value which has been used in at least one of the 0.11 vault versions and 'type' (correct current value).

Comment (tyrannosaurus-becks) [reply vault/resource_gcp_auth_backend_role.go]: Thanks!

**Comment by tyrannosaurus-becks** [comment]
Saw you pushed some code! I noticed there's a test failure that looks related:
```
--- FAIL: TestGCPAuthBackendRole_gce (0.06s)
    testing.go:434: Step 0 error: Check failed: Expected type (type in state) of "auth/tf-test-gcp-backend-3800239246745760615/role/tf-test-gcp-role-294652960337314985" to be "gce", got %!q(<nil>)
```

**Comment by Phylu** [comment]
The latest changes fix the failing acceptance tests. I had to revert the change that I made to the test where I renamed the expected attribute as well. This might be needed to change, later when the tests run with a newer version of vault.

**Comment by tyrannosaurus-becks** [comment]
@Phylu oddly I now get the following error when I try to run that test on this branch:
```
./resource_aws_secret_backend_role.go:48:5: cannot use util.JsonDiffSuppress (type func(string, string, string, *"github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema".ResourceData) bool) as type "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/schema".SchemaDiffSuppressFunc in field value
./resource_aws_secret_backend_role_test.go:33:36: cannot use util.TestCheckResourceAttrJSON("vault_aws_secret_backend_role.test_policy_inline", "policy", testAccAWSSecretBackendRolePolicyInline_basic) (type "github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc) as type "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc in argument to "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".ComposeTestCheckFunc
./resource_aws_secret_backend_role_test.go:44:36: cannot use util.TestCheckResourceAttrJSON("vault_aws_secret_backend_role.test_policy_inline", "policy", testAccAWSSecretBackendRolePolicyInline_updated) (type "github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc) as type "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc in argument to "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".ComposeTestCheckFunc
./resource_aws_secret_backend_role_test.go:68:36: cannot use util.TestCheckResourceAttrJSON("vault_aws_secret_backend_role.test_policy_inline", "policy", testAccAWSSecretBackendRolePolicyInline_basic) (type "github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc) as type "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc in argument to "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".ComposeTestCheckFunc
./resource_aws_secret_backend_role_test.go:102:36: cannot use util.TestCheckResourceAttrJSON("vault_aws_secret_backend_role.test_policy_inline", "policy", testAccAWSSecretBackendRolePolicyInline_basic) (type "github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc) as type "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc in argument to "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".ComposeTestCheckFunc
./resource_aws_secret_backend_role_test.go:113:36: cannot use util.TestCheckResourceAttrJSON("vault_aws_secret_backend_role.test_policy_inline", "policy", testAccAWSSecretBackendRolePolicyInline_updated) (type "github.com/terraform-providers/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc) as type "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".TestCheckFunc in argument to "github.com/Phylu/terraform-provider-vault/vendor/github.com/hashicorp/terraform/helper/resource".ComposeTestCheckFunc
```
I think the current master branch of the Terraform Vault Provider may just need to be merged in.

**Comment by Phylu** [comment]
That is very strange. Might it be an issue if you ran the tests in my repository, as some links to files in the vendor folder might be wrong?

 I just merged the current master and ran the acceptance tests again and everything seems fine. Let's see what travis says here. If I can do anything more, just let me know.

**Comment by Phylu** [comment]
> @Phylu yes, it did turn out to be an issue with my test environment. Thank you! This is looking fantastic and all tests are passing.

Nice. Thanks!
